name: Build and Deploy Blazor WASM + Slovnik

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Publish Blazor WASM
      run: dotnet publish ReadSlovnik/ReadSlovnik.csproj -c Release -o build

    - name: Prepare public folder
      run: |
        mkdir public
        cp -r build/wwwroot/* public/
        cp main.slovnik.txt public/

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: public

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
